// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: debug/debug.proto

package debugpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DebugContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InjectMemory  bool                   `protobuf:"varint,1,opt,name=inject_memory,json=injectMemory,proto3" json:"inject_memory,omitempty"`
	InjectSkills  bool                   `protobuf:"varint,2,opt,name=inject_skills,json=injectSkills,proto3" json:"inject_skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugContext) Reset() {
	*x = DebugContext{}
	mi := &file_debug_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugContext) ProtoMessage() {}

func (x *DebugContext) ProtoReflect() protoreflect.Message {
	mi := &file_debug_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugContext.ProtoReflect.Descriptor instead.
func (*DebugContext) Descriptor() ([]byte, []int) {
	return file_debug_debug_proto_rawDescGZIP(), []int{0}
}

func (x *DebugContext) GetInjectMemory() bool {
	if x != nil {
		return x.InjectMemory
	}
	return false
}

func (x *DebugContext) GetInjectSkills() bool {
	if x != nil {
		return x.InjectSkills
	}
	return false
}

type DebugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FileContext   string                 `protobuf:"bytes,2,opt,name=file_context,json=fileContext,proto3" json:"file_context,omitempty"` // optional source file content
	DiffContext   string                 `protobuf:"bytes,3,opt,name=diff_context,json=diffContext,proto3" json:"diff_context,omitempty"` // optional git diff
	Context       *DebugContext          `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugRequest) Reset() {
	*x = DebugRequest{}
	mi := &file_debug_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugRequest) ProtoMessage() {}

func (x *DebugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debug_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugRequest.ProtoReflect.Descriptor instead.
func (*DebugRequest) Descriptor() ([]byte, []int) {
	return file_debug_debug_proto_rawDescGZIP(), []int{1}
}

func (x *DebugRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DebugRequest) GetFileContext() string {
	if x != nil {
		return x.FileContext
	}
	return ""
}

func (x *DebugRequest) GetDiffContext() string {
	if x != nil {
		return x.DiffContext
	}
	return ""
}

func (x *DebugRequest) GetContext() *DebugContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ContextUsed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryHits    []string               `protobuf:"bytes,1,rep,name=memory_hits,json=memoryHits,proto3" json:"memory_hits,omitempty"`
	SkillHits     []string               `protobuf:"bytes,2,rep,name=skill_hits,json=skillHits,proto3" json:"skill_hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextUsed) Reset() {
	*x = ContextUsed{}
	mi := &file_debug_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextUsed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextUsed) ProtoMessage() {}

func (x *ContextUsed) ProtoReflect() protoreflect.Message {
	mi := &file_debug_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextUsed.ProtoReflect.Descriptor instead.
func (*ContextUsed) Descriptor() ([]byte, []int) {
	return file_debug_debug_proto_rawDescGZIP(), []int{2}
}

func (x *ContextUsed) GetMemoryHits() []string {
	if x != nil {
		return x.MemoryHits
	}
	return nil
}

func (x *ContextUsed) GetSkillHits() []string {
	if x != nil {
		return x.SkillHits
	}
	return nil
}

type DebugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootCause     string                 `protobuf:"bytes,1,opt,name=root_cause,json=rootCause,proto3" json:"root_cause,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Confidence    string                 `protobuf:"bytes,3,opt,name=confidence,proto3" json:"confidence,omitempty"` // HIGH | MEDIUM | LOW
	SuggestedFix  string                 `protobuf:"bytes,4,opt,name=suggested_fix,json=suggestedFix,proto3" json:"suggested_fix,omitempty"`
	SimilarIssues []string               `protobuf:"bytes,5,rep,name=similar_issues,json=similarIssues,proto3" json:"similar_issues,omitempty"`
	FollowUp      string                 `protobuf:"bytes,6,opt,name=follow_up,json=followUp,proto3" json:"follow_up,omitempty"`
	ContextUsed   *ContextUsed           `protobuf:"bytes,7,opt,name=context_used,json=contextUsed,proto3" json:"context_used,omitempty"`
	Model         string                 `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugResponse) Reset() {
	*x = DebugResponse{}
	mi := &file_debug_debug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugResponse) ProtoMessage() {}

func (x *DebugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debug_debug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugResponse.ProtoReflect.Descriptor instead.
func (*DebugResponse) Descriptor() ([]byte, []int) {
	return file_debug_debug_proto_rawDescGZIP(), []int{3}
}

func (x *DebugResponse) GetRootCause() string {
	if x != nil {
		return x.RootCause
	}
	return ""
}

func (x *DebugResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *DebugResponse) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *DebugResponse) GetSuggestedFix() string {
	if x != nil {
		return x.SuggestedFix
	}
	return ""
}

func (x *DebugResponse) GetSimilarIssues() []string {
	if x != nil {
		return x.SimilarIssues
	}
	return nil
}

func (x *DebugResponse) GetFollowUp() string {
	if x != nil {
		return x.FollowUp
	}
	return ""
}

func (x *DebugResponse) GetContextUsed() *ContextUsed {
	if x != nil {
		return x.ContextUsed
	}
	return nil
}

func (x *DebugResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_debug_debug_proto protoreflect.FileDescriptor

const file_debug_debug_proto_rawDesc = "" +
	"\n" +
	"\x11debug/debug.proto\x12\x05debug\"X\n" +
	"\fDebugContext\x12#\n" +
	"\rinject_memory\x18\x01 \x01(\bR\finjectMemory\x12#\n" +
	"\rinject_skills\x18\x02 \x01(\bR\finjectSkills\"\xa8\x01\n" +
	"\fDebugRequest\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\x12!\n" +
	"\ffile_context\x18\x02 \x01(\tR\vfileContext\x12!\n" +
	"\fdiff_context\x18\x03 \x01(\tR\vdiffContext\x12-\n" +
	"\acontext\x18\x04 \x01(\v2\x13.debug.DebugContextR\acontext\"M\n" +
	"\vContextUsed\x12\x1f\n" +
	"\vmemory_hits\x18\x01 \x03(\tR\n" +
	"memoryHits\x12\x1d\n" +
	"\n" +
	"skill_hits\x18\x02 \x03(\tR\tskillHits\"\xa0\x02\n" +
	"\rDebugResponse\x12\x1d\n" +
	"\n" +
	"root_cause\x18\x01 \x01(\tR\trootCause\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\tR\n" +
	"confidence\x12#\n" +
	"\rsuggested_fix\x18\x04 \x01(\tR\fsuggestedFix\x12%\n" +
	"\x0esimilar_issues\x18\x05 \x03(\tR\rsimilarIssues\x12\x1b\n" +
	"\tfollow_up\x18\x06 \x01(\tR\bfollowUp\x125\n" +
	"\fcontext_used\x18\a \x01(\v2\x12.debug.ContextUsedR\vcontextUsed\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model2B\n" +
	"\fDebugService\x122\n" +
	"\x05Debug\x12\x13.debug.DebugRequest\x1a\x14.debug.DebugResponseB-Z+github.com/trungtran/coder/api/grpc/debugpbb\x06proto3"

var (
	file_debug_debug_proto_rawDescOnce sync.Once
	file_debug_debug_proto_rawDescData []byte
)

func file_debug_debug_proto_rawDescGZIP() []byte {
	file_debug_debug_proto_rawDescOnce.Do(func() {
		file_debug_debug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_debug_debug_proto_rawDesc), len(file_debug_debug_proto_rawDesc)))
	})
	return file_debug_debug_proto_rawDescData
}

var file_debug_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_debug_debug_proto_goTypes = []any{
	(*DebugContext)(nil),  // 0: debug.DebugContext
	(*DebugRequest)(nil),  // 1: debug.DebugRequest
	(*ContextUsed)(nil),   // 2: debug.ContextUsed
	(*DebugResponse)(nil), // 3: debug.DebugResponse
}
var file_debug_debug_proto_depIdxs = []int32{
	0, // 0: debug.DebugRequest.context:type_name -> debug.DebugContext
	2, // 1: debug.DebugResponse.context_used:type_name -> debug.ContextUsed
	1, // 2: debug.DebugService.Debug:input_type -> debug.DebugRequest
	3, // 3: debug.DebugService.Debug:output_type -> debug.DebugResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_debug_debug_proto_init() }
func file_debug_debug_proto_init() {
	if File_debug_debug_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_debug_debug_proto_rawDesc), len(file_debug_debug_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_debug_debug_proto_goTypes,
		DependencyIndexes: file_debug_debug_proto_depIdxs,
		MessageInfos:      file_debug_debug_proto_msgTypes,
	}.Build()
	File_debug_debug_proto = out.File
	file_debug_debug_proto_goTypes = nil
	file_debug_debug_proto_depIdxs = nil
}
