// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: chat/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InjectMemory  bool                   `protobuf:"varint,1,opt,name=inject_memory,json=injectMemory,proto3" json:"inject_memory,omitempty"`
	InjectSkills  bool                   `protobuf:"varint,2,opt,name=inject_skills,json=injectSkills,proto3" json:"inject_skills,omitempty"`
	MemoryLimit   int32                  `protobuf:"varint,3,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	SkillLimit    int32                  `protobuf:"varint,4,opt,name=skill_limit,json=skillLimit,proto3" json:"skill_limit,omitempty"`
	ExtraSystem   string                 `protobuf:"bytes,5,opt,name=extra_system,json=extraSystem,proto3" json:"extra_system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatContext) Reset() {
	*x = ChatContext{}
	mi := &file_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatContext) ProtoMessage() {}

func (x *ChatContext) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatContext.ProtoReflect.Descriptor instead.
func (*ChatContext) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatContext) GetInjectMemory() bool {
	if x != nil {
		return x.InjectMemory
	}
	return false
}

func (x *ChatContext) GetInjectSkills() bool {
	if x != nil {
		return x.InjectSkills
	}
	return false
}

func (x *ChatContext) GetMemoryLimit() int32 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *ChatContext) GetSkillLimit() int32 {
	if x != nil {
		return x.SkillLimit
	}
	return 0
}

func (x *ChatContext) GetExtraSystem() string {
	if x != nil {
		return x.ExtraSystem
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // optional — resume existing session
	Context       *ChatContext           `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetContext() *ChatContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ContextUsed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryHits    []string               `protobuf:"bytes,1,rep,name=memory_hits,json=memoryHits,proto3" json:"memory_hits,omitempty"`
	SkillHits     []string               `protobuf:"bytes,2,rep,name=skill_hits,json=skillHits,proto3" json:"skill_hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextUsed) Reset() {
	*x = ContextUsed{}
	mi := &file_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextUsed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextUsed) ProtoMessage() {}

func (x *ContextUsed) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextUsed.ProtoReflect.Descriptor instead.
func (*ContextUsed) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ContextUsed) GetMemoryHits() []string {
	if x != nil {
		return x.MemoryHits
	}
	return nil
}

func (x *ContextUsed) GetSkillHits() []string {
	if x != nil {
		return x.SkillHits
	}
	return nil
}

type TokenUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        int32                  `protobuf:"varint,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Completion    int32                  `protobuf:"varint,2,opt,name=completion,proto3" json:"completion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_chat_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *TokenUsage) GetPrompt() int32 {
	if x != nil {
		return x.Prompt
	}
	return 0
}

func (x *TokenUsage) GetCompletion() int32 {
	if x != nil {
		return x.Completion
	}
	return 0
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ContextUsed   *ContextUsed           `protobuf:"bytes,3,opt,name=context_used,json=contextUsed,proto3" json:"context_used,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Tokens        *TokenUsage            `protobuf:"bytes,5,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_chat_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResponse) GetContextUsed() *ContextUsed {
	if x != nil {
		return x.ContextUsed
	}
	return nil
}

func (x *ChatResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatResponse) GetTokens() *TokenUsage {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// ChatStreamResponse is sent multiple times during streaming.
// Each frame carries either a delta token OR the final metadata (done=true).
type ChatStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"` // token chunk; empty when done=true
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`       // set on the final frame
	ContextUsed   *ContextUsed           `protobuf:"bytes,4,opt,name=context_used,json=contextUsed,proto3" json:"context_used,omitempty"` // set on the final frame
	Tokens        *TokenUsage            `protobuf:"bytes,5,opt,name=tokens,proto3" json:"tokens,omitempty"`                              // set on the final frame
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                                // set if an error occurred mid-stream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamResponse) Reset() {
	*x = ChatStreamResponse{}
	mi := &file_chat_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamResponse) ProtoMessage() {}

func (x *ChatStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamResponse.ProtoReflect.Descriptor instead.
func (*ChatStreamResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ChatStreamResponse) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *ChatStreamResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatStreamResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatStreamResponse) GetContextUsed() *ContextUsed {
	if x != nil {
		return x.ContextUsed
	}
	return nil
}

func (x *ChatStreamResponse) GetTokens() *TokenUsage {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ChatStreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_chat_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{6}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Session) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	TokensIn      int32                  `protobuf:"varint,5,opt,name=tokens_in,json=tokensIn,proto3" json:"tokens_in,omitempty"`
	TokensOut     int32                  `protobuf:"varint,6,opt,name=tokens_out,json=tokensOut,proto3" json:"tokens_out,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chat_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTokensIn() int32 {
	if x != nil {
		return x.TokensIn
	}
	return 0
}

func (x *Message) GetTokensOut() int32 {
	if x != nil {
		return x.TokensOut
	}
	return 0
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_chat_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{8}
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_chat_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_chat_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{10}
}

func (x *GetSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_chat_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{11}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetSessionResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_chat_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_chat_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_chat_chat_proto protoreflect.FileDescriptor

const file_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x0fchat/chat.proto\x12\x04chat\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n" +
	"\vChatContext\x12#\n" +
	"\rinject_memory\x18\x01 \x01(\bR\finjectMemory\x12#\n" +
	"\rinject_skills\x18\x02 \x01(\bR\finjectSkills\x12!\n" +
	"\fmemory_limit\x18\x03 \x01(\x05R\vmemoryLimit\x12\x1f\n" +
	"\vskill_limit\x18\x04 \x01(\x05R\n" +
	"skillLimit\x12!\n" +
	"\fextra_system\x18\x05 \x01(\tR\vextraSystem\"s\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12+\n" +
	"\acontext\x18\x03 \x01(\v2\x11.chat.ChatContextR\acontext\"M\n" +
	"\vContextUsed\x12\x1f\n" +
	"\vmemory_hits\x18\x01 \x03(\tR\n" +
	"memoryHits\x12\x1d\n" +
	"\n" +
	"skill_hits\x18\x02 \x03(\tR\tskillHits\"D\n" +
	"\n" +
	"TokenUsage\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\x05R\x06prompt\x12\x1e\n" +
	"\n" +
	"completion\x18\x02 \x01(\x05R\n" +
	"completion\"\xb9\x01\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x124\n" +
	"\fcontext_used\x18\x03 \x01(\v2\x11.chat.ContextUsedR\vcontextUsed\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12(\n" +
	"\x06tokens\x18\x05 \x01(\v2\x10.chat.TokenUsageR\x06tokens\"\xd3\x01\n" +
	"\x12ChatStreamResponse\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x124\n" +
	"\fcontext_used\x18\x04 \x01(\v2\x11.chat.ContextUsedR\vcontextUsed\x12(\n" +
	"\x06tokens\x18\x05 \x01(\v2\x10.chat.TokenUsageR\x06tokens\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xc2\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdd\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1b\n" +
	"\ttokens_in\x18\x05 \x01(\x05R\btokensIn\x12\x1d\n" +
	"\n" +
	"tokens_out\x18\x06 \x01(\x05R\ttokensOut\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"+\n" +
	"\x13ListSessionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"A\n" +
	"\x14ListSessionsResponse\x12)\n" +
	"\bsessions\x18\x01 \x03(\v2\r.chat.SessionR\bsessions\"#\n" +
	"\x11GetSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"h\n" +
	"\x12GetSessionResponse\x12'\n" +
	"\asession\x18\x01 \x01(\v2\r.chat.SessionR\asession\x12)\n" +
	"\bmessages\x18\x02 \x03(\v2\r.chat.MessageR\bmessages\"&\n" +
	"\x14DeleteSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcb\x02\n" +
	"\vChatService\x12-\n" +
	"\x04Chat\x12\x11.chat.ChatRequest\x1a\x12.chat.ChatResponse\x12;\n" +
	"\n" +
	"ChatStream\x12\x11.chat.ChatRequest\x1a\x18.chat.ChatStreamResponse0\x01\x12E\n" +
	"\fListSessions\x12\x19.chat.ListSessionsRequest\x1a\x1a.chat.ListSessionsResponse\x12?\n" +
	"\n" +
	"GetSession\x12\x17.chat.GetSessionRequest\x1a\x18.chat.GetSessionResponse\x12H\n" +
	"\rDeleteSession\x12\x1a.chat.DeleteSessionRequest\x1a\x1b.chat.DeleteSessionResponseB,Z*github.com/trungtran/coder/api/grpc/chatpbb\x06proto3"

var (
	file_chat_chat_proto_rawDescOnce sync.Once
	file_chat_chat_proto_rawDescData []byte
)

func file_chat_chat_proto_rawDescGZIP() []byte {
	file_chat_chat_proto_rawDescOnce.Do(func() {
		file_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_chat_proto_rawDesc), len(file_chat_chat_proto_rawDesc)))
	})
	return file_chat_chat_proto_rawDescData
}

var file_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_chat_chat_proto_goTypes = []any{
	(*ChatContext)(nil),           // 0: chat.ChatContext
	(*ChatRequest)(nil),           // 1: chat.ChatRequest
	(*ContextUsed)(nil),           // 2: chat.ContextUsed
	(*TokenUsage)(nil),            // 3: chat.TokenUsage
	(*ChatResponse)(nil),          // 4: chat.ChatResponse
	(*ChatStreamResponse)(nil),    // 5: chat.ChatStreamResponse
	(*Session)(nil),               // 6: chat.Session
	(*Message)(nil),               // 7: chat.Message
	(*ListSessionsRequest)(nil),   // 8: chat.ListSessionsRequest
	(*ListSessionsResponse)(nil),  // 9: chat.ListSessionsResponse
	(*GetSessionRequest)(nil),     // 10: chat.GetSessionRequest
	(*GetSessionResponse)(nil),    // 11: chat.GetSessionResponse
	(*DeleteSessionRequest)(nil),  // 12: chat.DeleteSessionRequest
	(*DeleteSessionResponse)(nil), // 13: chat.DeleteSessionResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_chat_chat_proto_depIdxs = []int32{
	0,  // 0: chat.ChatRequest.context:type_name -> chat.ChatContext
	2,  // 1: chat.ChatResponse.context_used:type_name -> chat.ContextUsed
	3,  // 2: chat.ChatResponse.tokens:type_name -> chat.TokenUsage
	2,  // 3: chat.ChatStreamResponse.context_used:type_name -> chat.ContextUsed
	3,  // 4: chat.ChatStreamResponse.tokens:type_name -> chat.TokenUsage
	14, // 5: chat.Session.created_at:type_name -> google.protobuf.Timestamp
	14, // 6: chat.Session.updated_at:type_name -> google.protobuf.Timestamp
	14, // 7: chat.Message.created_at:type_name -> google.protobuf.Timestamp
	6,  // 8: chat.ListSessionsResponse.sessions:type_name -> chat.Session
	6,  // 9: chat.GetSessionResponse.session:type_name -> chat.Session
	7,  // 10: chat.GetSessionResponse.messages:type_name -> chat.Message
	1,  // 11: chat.ChatService.Chat:input_type -> chat.ChatRequest
	1,  // 12: chat.ChatService.ChatStream:input_type -> chat.ChatRequest
	8,  // 13: chat.ChatService.ListSessions:input_type -> chat.ListSessionsRequest
	10, // 14: chat.ChatService.GetSession:input_type -> chat.GetSessionRequest
	12, // 15: chat.ChatService.DeleteSession:input_type -> chat.DeleteSessionRequest
	4,  // 16: chat.ChatService.Chat:output_type -> chat.ChatResponse
	5,  // 17: chat.ChatService.ChatStream:output_type -> chat.ChatStreamResponse
	9,  // 18: chat.ChatService.ListSessions:output_type -> chat.ListSessionsResponse
	11, // 19: chat.ChatService.GetSession:output_type -> chat.GetSessionResponse
	13, // 20: chat.ChatService.DeleteSession:output_type -> chat.DeleteSessionResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_chat_chat_proto_init() }
func file_chat_chat_proto_init() {
	if File_chat_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_chat_proto_rawDesc), len(file_chat_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_chat_proto_goTypes,
		DependencyIndexes: file_chat_chat_proto_depIdxs,
		MessageInfos:      file_chat_chat_proto_msgTypes,
	}.Build()
	File_chat_chat_proto = out.File
	file_chat_chat_proto_goTypes = nil
	file_chat_chat_proto_depIdxs = nil
}
