// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: review/review.proto

package reviewpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InjectMemory  bool                   `protobuf:"varint,1,opt,name=inject_memory,json=injectMemory,proto3" json:"inject_memory,omitempty"`
	InjectSkills  bool                   `protobuf:"varint,2,opt,name=inject_skills,json=injectSkills,proto3" json:"inject_skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewContext) Reset() {
	*x = ReviewContext{}
	mi := &file_review_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewContext) ProtoMessage() {}

func (x *ReviewContext) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewContext.ProtoReflect.Descriptor instead.
func (*ReviewContext) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewContext) GetInjectMemory() bool {
	if x != nil {
		return x.InjectMemory
	}
	return false
}

func (x *ReviewContext) GetInjectSkills() bool {
	if x != nil {
		return x.InjectSkills
	}
	return false
}

type ReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // diff | file | pr
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Focus         string                 `protobuf:"bytes,3,opt,name=focus,proto3" json:"focus,omitempty"` // optional: security, performance, etc.
	Context       *ReviewContext         `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewRequest) Reset() {
	*x = ReviewRequest{}
	mi := &file_review_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRequest) ProtoMessage() {}

func (x *ReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRequest.ProtoReflect.Descriptor instead.
func (*ReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReviewRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReviewRequest) GetFocus() string {
	if x != nil {
		return x.Focus
	}
	return ""
}

func (x *ReviewRequest) GetContext() *ReviewContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ReviewConcern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"` // HIGH | MEDIUM | LOW
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Suggestion    string                 `protobuf:"bytes,4,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewConcern) Reset() {
	*x = ReviewConcern{}
	mi := &file_review_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewConcern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewConcern) ProtoMessage() {}

func (x *ReviewConcern) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewConcern.ProtoReflect.Descriptor instead.
func (*ReviewConcern) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{2}
}

func (x *ReviewConcern) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ReviewConcern) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReviewConcern) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ReviewConcern) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

type ReviewStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FilesReviewed  int32                  `protobuf:"varint,1,opt,name=files_reviewed,json=filesReviewed,proto3" json:"files_reviewed,omitempty"`
	ConcernsHigh   int32                  `protobuf:"varint,2,opt,name=concerns_high,json=concernsHigh,proto3" json:"concerns_high,omitempty"`
	ConcernsMedium int32                  `protobuf:"varint,3,opt,name=concerns_medium,json=concernsMedium,proto3" json:"concerns_medium,omitempty"`
	ConcernsLow    int32                  `protobuf:"varint,4,opt,name=concerns_low,json=concernsLow,proto3" json:"concerns_low,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReviewStats) Reset() {
	*x = ReviewStats{}
	mi := &file_review_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewStats) ProtoMessage() {}

func (x *ReviewStats) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewStats.ProtoReflect.Descriptor instead.
func (*ReviewStats) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{3}
}

func (x *ReviewStats) GetFilesReviewed() int32 {
	if x != nil {
		return x.FilesReviewed
	}
	return 0
}

func (x *ReviewStats) GetConcernsHigh() int32 {
	if x != nil {
		return x.ConcernsHigh
	}
	return 0
}

func (x *ReviewStats) GetConcernsMedium() int32 {
	if x != nil {
		return x.ConcernsMedium
	}
	return 0
}

func (x *ReviewStats) GetConcernsLow() int32 {
	if x != nil {
		return x.ConcernsLow
	}
	return 0
}

type ContextUsed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryHits    []string               `protobuf:"bytes,1,rep,name=memory_hits,json=memoryHits,proto3" json:"memory_hits,omitempty"`
	SkillHits     []string               `protobuf:"bytes,2,rep,name=skill_hits,json=skillHits,proto3" json:"skill_hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextUsed) Reset() {
	*x = ContextUsed{}
	mi := &file_review_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextUsed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextUsed) ProtoMessage() {}

func (x *ContextUsed) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextUsed.ProtoReflect.Descriptor instead.
func (*ContextUsed) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{4}
}

func (x *ContextUsed) GetMemoryHits() []string {
	if x != nil {
		return x.MemoryHits
	}
	return nil
}

func (x *ContextUsed) GetSkillHits() []string {
	if x != nil {
		return x.SkillHits
	}
	return nil
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Strengths     []string               `protobuf:"bytes,2,rep,name=strengths,proto3" json:"strengths,omitempty"`
	Concerns      []*ReviewConcern       `protobuf:"bytes,3,rep,name=concerns,proto3" json:"concerns,omitempty"`
	Suggestions   []string               `protobuf:"bytes,4,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	Stats         *ReviewStats           `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	ContextUsed   *ContextUsed           `protobuf:"bytes,6,opt,name=context_used,json=contextUsed,proto3" json:"context_used,omitempty"`
	Model         string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_review_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{5}
}

func (x *ReviewResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ReviewResponse) GetStrengths() []string {
	if x != nil {
		return x.Strengths
	}
	return nil
}

func (x *ReviewResponse) GetConcerns() []*ReviewConcern {
	if x != nil {
		return x.Concerns
	}
	return nil
}

func (x *ReviewResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *ReviewResponse) GetStats() *ReviewStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ReviewResponse) GetContextUsed() *ContextUsed {
	if x != nil {
		return x.ContextUsed
	}
	return nil
}

func (x *ReviewResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_review_review_proto protoreflect.FileDescriptor

const file_review_review_proto_rawDesc = "" +
	"\n" +
	"\x13review/review.proto\x12\x06review\"Y\n" +
	"\rReviewContext\x12#\n" +
	"\rinject_memory\x18\x01 \x01(\bR\finjectMemory\x12#\n" +
	"\rinject_skills\x18\x02 \x01(\bR\finjectSkills\"\x84\x01\n" +
	"\rReviewRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05focus\x18\x03 \x01(\tR\x05focus\x12/\n" +
	"\acontext\x18\x04 \x01(\v2\x15.review.ReviewContextR\acontext\"\x89\x01\n" +
	"\rReviewConcern\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x04 \x01(\tR\n" +
	"suggestion\"\xa5\x01\n" +
	"\vReviewStats\x12%\n" +
	"\x0efiles_reviewed\x18\x01 \x01(\x05R\rfilesReviewed\x12#\n" +
	"\rconcerns_high\x18\x02 \x01(\x05R\fconcernsHigh\x12'\n" +
	"\x0fconcerns_medium\x18\x03 \x01(\x05R\x0econcernsMedium\x12!\n" +
	"\fconcerns_low\x18\x04 \x01(\x05R\vconcernsLow\"M\n" +
	"\vContextUsed\x12\x1f\n" +
	"\vmemory_hits\x18\x01 \x03(\tR\n" +
	"memoryHits\x12\x1d\n" +
	"\n" +
	"skill_hits\x18\x02 \x03(\tR\tskillHits\"\x96\x02\n" +
	"\x0eReviewResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x1c\n" +
	"\tstrengths\x18\x02 \x03(\tR\tstrengths\x121\n" +
	"\bconcerns\x18\x03 \x03(\v2\x15.review.ReviewConcernR\bconcerns\x12 \n" +
	"\vsuggestions\x18\x04 \x03(\tR\vsuggestions\x12)\n" +
	"\x05stats\x18\x05 \x01(\v2\x13.review.ReviewStatsR\x05stats\x126\n" +
	"\fcontext_used\x18\x06 \x01(\v2\x13.review.ContextUsedR\vcontextUsed\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model2H\n" +
	"\rReviewService\x127\n" +
	"\x06Review\x12\x15.review.ReviewRequest\x1a\x16.review.ReviewResponseB.Z,github.com/trungtran/coder/api/grpc/reviewpbb\x06proto3"

var (
	file_review_review_proto_rawDescOnce sync.Once
	file_review_review_proto_rawDescData []byte
)

func file_review_review_proto_rawDescGZIP() []byte {
	file_review_review_proto_rawDescOnce.Do(func() {
		file_review_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_review_proto_rawDesc), len(file_review_review_proto_rawDesc)))
	})
	return file_review_review_proto_rawDescData
}

var file_review_review_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_review_review_proto_goTypes = []any{
	(*ReviewContext)(nil),  // 0: review.ReviewContext
	(*ReviewRequest)(nil),  // 1: review.ReviewRequest
	(*ReviewConcern)(nil),  // 2: review.ReviewConcern
	(*ReviewStats)(nil),    // 3: review.ReviewStats
	(*ContextUsed)(nil),    // 4: review.ContextUsed
	(*ReviewResponse)(nil), // 5: review.ReviewResponse
}
var file_review_review_proto_depIdxs = []int32{
	0, // 0: review.ReviewRequest.context:type_name -> review.ReviewContext
	2, // 1: review.ReviewResponse.concerns:type_name -> review.ReviewConcern
	3, // 2: review.ReviewResponse.stats:type_name -> review.ReviewStats
	4, // 3: review.ReviewResponse.context_used:type_name -> review.ContextUsed
	1, // 4: review.ReviewService.Review:input_type -> review.ReviewRequest
	5, // 5: review.ReviewService.Review:output_type -> review.ReviewResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_review_review_proto_init() }
func file_review_review_proto_init() {
	if File_review_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_review_proto_rawDesc), len(file_review_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_review_proto_goTypes,
		DependencyIndexes: file_review_review_proto_depIdxs,
		MessageInfos:      file_review_review_proto_msgTypes,
	}.Build()
	File_review_review_proto = out.File
	file_review_review_proto_goTypes = nil
	file_review_review_proto_depIdxs = nil
}
