// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: skill/skill.proto

package skillpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestSkillRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SkillMdContent string                 `protobuf:"bytes,2,opt,name=skill_md_content,json=skillMdContent,proto3" json:"skill_md_content,omitempty"`
	Rules          []*RuleFileEntry       `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	Source         string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // "local", "antigravity", "custom"
	SourceRepo     string                 `protobuf:"bytes,5,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	Category       string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IngestSkillRequest) Reset() {
	*x = IngestSkillRequest{}
	mi := &file_skill_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSkillRequest) ProtoMessage() {}

func (x *IngestSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSkillRequest.ProtoReflect.Descriptor instead.
func (*IngestSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{0}
}

func (x *IngestSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IngestSkillRequest) GetSkillMdContent() string {
	if x != nil {
		return x.SkillMdContent
	}
	return ""
}

func (x *IngestSkillRequest) GetRules() []*RuleFileEntry {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *IngestSkillRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IngestSkillRequest) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *IngestSkillRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type RuleFileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleFileEntry) Reset() {
	*x = RuleFileEntry{}
	mi := &file_skill_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleFileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleFileEntry) ProtoMessage() {}

func (x *RuleFileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleFileEntry.ProtoReflect.Descriptor instead.
func (*RuleFileEntry) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{1}
}

func (x *RuleFileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RuleFileEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type IngestSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	ChunksTotal   int32                  `protobuf:"varint,2,opt,name=chunks_total,json=chunksTotal,proto3" json:"chunks_total,omitempty"`
	ChunksNew     int32                  `protobuf:"varint,3,opt,name=chunks_new,json=chunksNew,proto3" json:"chunks_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSkillResponse) Reset() {
	*x = IngestSkillResponse{}
	mi := &file_skill_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSkillResponse) ProtoMessage() {}

func (x *IngestSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSkillResponse.ProtoReflect.Descriptor instead.
func (*IngestSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{2}
}

func (x *IngestSkillResponse) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *IngestSkillResponse) GetChunksTotal() int32 {
	if x != nil {
		return x.ChunksTotal
	}
	return 0
}

func (x *IngestSkillResponse) GetChunksNew() int32 {
	if x != nil {
		return x.ChunksNew
	}
	return 0
}

type SearchSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSkillsRequest) Reset() {
	*x = SearchSkillsRequest{}
	mi := &file_skill_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSkillsRequest) ProtoMessage() {}

func (x *SearchSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSkillsRequest.ProtoReflect.Descriptor instead.
func (*SearchSkillsRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{3}
}

func (x *SearchSkillsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchSkillsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SkillSearchResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSkillsResponse) Reset() {
	*x = SearchSkillsResponse{}
	mi := &file_skill_skill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSkillsResponse) ProtoMessage() {}

func (x *SearchSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSkillsResponse.ProtoReflect.Descriptor instead.
func (*SearchSkillsResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{4}
}

func (x *SearchSkillsResponse) GetResults() []*SkillSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SkillSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *SkillInfo             `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	Chunks        []*SkillChunkResult    `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillSearchResult) Reset() {
	*x = SkillSearchResult{}
	mi := &file_skill_skill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillSearchResult) ProtoMessage() {}

func (x *SkillSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillSearchResult.ProtoReflect.Descriptor instead.
func (*SkillSearchResult) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{5}
}

func (x *SkillSearchResult) GetSkill() *SkillInfo {
	if x != nil {
		return x.Skill
	}
	return nil
}

func (x *SkillSearchResult) GetChunks() []*SkillChunkResult {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *SkillSearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SkillInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	SourceRepo    string                 `protobuf:"bytes,6,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	Risk          string                 `protobuf:"bytes,7,opt,name=risk,proto3" json:"risk,omitempty"`
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,10,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillInfo) Reset() {
	*x = SkillInfo{}
	mi := &file_skill_skill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillInfo) ProtoMessage() {}

func (x *SkillInfo) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillInfo.ProtoReflect.Descriptor instead.
func (*SkillInfo) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{6}
}

func (x *SkillInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SkillInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SkillInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SkillInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SkillInfo) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *SkillInfo) GetRisk() string {
	if x != nil {
		return x.Risk
	}
	return ""
}

func (x *SkillInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SkillInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SkillInfo) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *SkillInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SkillInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SkillChunkResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SkillId       string                 `protobuf:"bytes,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	ChunkType     string                 `protobuf:"bytes,3,opt,name=chunk_type,json=chunkType,proto3" json:"chunk_type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,6,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Score         float32                `protobuf:"fixed32,7,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillChunkResult) Reset() {
	*x = SkillChunkResult{}
	mi := &file_skill_skill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillChunkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillChunkResult) ProtoMessage() {}

func (x *SkillChunkResult) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillChunkResult.ProtoReflect.Descriptor instead.
func (*SkillChunkResult) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{7}
}

func (x *SkillChunkResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SkillChunkResult) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *SkillChunkResult) GetChunkType() string {
	if x != nil {
		return x.ChunkType
	}
	return ""
}

func (x *SkillChunkResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SkillChunkResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SkillChunkResult) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *SkillChunkResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ListSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsRequest) Reset() {
	*x = ListSkillsRequest{}
	mi := &file_skill_skill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsRequest) ProtoMessage() {}

func (x *ListSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsRequest.ProtoReflect.Descriptor instead.
func (*ListSkillsRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{8}
}

func (x *ListSkillsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListSkillsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListSkillsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSkillsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*SkillInfo           `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsResponse) Reset() {
	*x = ListSkillsResponse{}
	mi := &file_skill_skill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsResponse) ProtoMessage() {}

func (x *ListSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsResponse.ProtoReflect.Descriptor instead.
func (*ListSkillsResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{9}
}

func (x *ListSkillsResponse) GetSkills() []*SkillInfo {
	if x != nil {
		return x.Skills
	}
	return nil
}

type GetSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillRequest) Reset() {
	*x = GetSkillRequest{}
	mi := &file_skill_skill_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillRequest) ProtoMessage() {}

func (x *GetSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillRequest.ProtoReflect.Descriptor instead.
func (*GetSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{10}
}

func (x *GetSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *SkillInfo             `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	Chunks        []*SkillChunkResult    `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillResponse) Reset() {
	*x = GetSkillResponse{}
	mi := &file_skill_skill_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillResponse) ProtoMessage() {}

func (x *GetSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillResponse.ProtoReflect.Descriptor instead.
func (*GetSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{11}
}

func (x *GetSkillResponse) GetSkill() *SkillInfo {
	if x != nil {
		return x.Skill
	}
	return nil
}

func (x *GetSkillResponse) GetChunks() []*SkillChunkResult {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type DeleteSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillRequest) Reset() {
	*x = DeleteSkillRequest{}
	mi := &file_skill_skill_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillRequest) ProtoMessage() {}

func (x *DeleteSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillRequest.ProtoReflect.Descriptor instead.
func (*DeleteSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillResponse) Reset() {
	*x = DeleteSkillResponse{}
	mi := &file_skill_skill_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillResponse) ProtoMessage() {}

func (x *DeleteSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillResponse.ProtoReflect.Descriptor instead.
func (*DeleteSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSkillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_skill_skill_proto protoreflect.FileDescriptor

const file_skill_skill_proto_rawDesc = "" +
	"\n" +
	"\x11skill/skill.proto\x12\x05skill\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\x12IngestSkillRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x10skill_md_content\x18\x02 \x01(\tR\x0eskillMdContent\x12*\n" +
	"\x05rules\x18\x03 \x03(\v2\x14.skill.RuleFileEntryR\x05rules\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1f\n" +
	"\vsource_repo\x18\x05 \x01(\tR\n" +
	"sourceRepo\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\"=\n" +
	"\rRuleFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"r\n" +
	"\x13IngestSkillResponse\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12!\n" +
	"\fchunks_total\x18\x02 \x01(\x05R\vchunksTotal\x12\x1d\n" +
	"\n" +
	"chunks_new\x18\x03 \x01(\x05R\tchunksNew\"A\n" +
	"\x13SearchSkillsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"J\n" +
	"\x14SearchSkillsResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.skill.SkillSearchResultR\aresults\"\x82\x01\n" +
	"\x11SkillSearchResult\x12&\n" +
	"\x05skill\x18\x01 \x01(\v2\x10.skill.SkillInfoR\x05skill\x12/\n" +
	"\x06chunks\x18\x02 \x03(\v2\x17.skill.SkillChunkResultR\x06chunks\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"\xff\x02\n" +
	"\tSkillInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1f\n" +
	"\vsource_repo\x18\x06 \x01(\tR\n" +
	"sourceRepo\x12\x12\n" +
	"\x04risk\x18\a \x01(\tR\x04risk\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x1f\n" +
	"\vchunk_count\x18\n" +
	" \x01(\x05R\n" +
	"chunkCount\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc3\x01\n" +
	"\x10SkillChunkResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\tR\askillId\x12\x1d\n" +
	"\n" +
	"chunk_type\x18\x03 \x01(\tR\tchunkType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1f\n" +
	"\vchunk_index\x18\x06 \x01(\x05R\n" +
	"chunkIndex\x12\x14\n" +
	"\x05score\x18\a \x01(\x02R\x05score\"u\n" +
	"\x11ListSkillsRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\">\n" +
	"\x12ListSkillsResponse\x12(\n" +
	"\x06skills\x18\x01 \x03(\v2\x10.skill.SkillInfoR\x06skills\"%\n" +
	"\x0fGetSkillRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"k\n" +
	"\x10GetSkillResponse\x12&\n" +
	"\x05skill\x18\x01 \x01(\v2\x10.skill.SkillInfoR\x05skill\x12/\n" +
	"\x06chunks\x18\x02 \x03(\v2\x17.skill.SkillChunkResultR\x06chunks\"(\n" +
	"\x12DeleteSkillRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x13DeleteSkillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe3\x02\n" +
	"\fSkillService\x12D\n" +
	"\vIngestSkill\x12\x19.skill.IngestSkillRequest\x1a\x1a.skill.IngestSkillResponse\x12G\n" +
	"\fSearchSkills\x12\x1a.skill.SearchSkillsRequest\x1a\x1b.skill.SearchSkillsResponse\x12A\n" +
	"\n" +
	"ListSkills\x12\x18.skill.ListSkillsRequest\x1a\x19.skill.ListSkillsResponse\x12;\n" +
	"\bGetSkill\x12\x16.skill.GetSkillRequest\x1a\x17.skill.GetSkillResponse\x12D\n" +
	"\vDeleteSkill\x12\x19.skill.DeleteSkillRequest\x1a\x1a.skill.DeleteSkillResponseB-Z+github.com/trungtran/coder/api/grpc/skillpbb\x06proto3"

var (
	file_skill_skill_proto_rawDescOnce sync.Once
	file_skill_skill_proto_rawDescData []byte
)

func file_skill_skill_proto_rawDescGZIP() []byte {
	file_skill_skill_proto_rawDescOnce.Do(func() {
		file_skill_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skill_skill_proto_rawDesc), len(file_skill_skill_proto_rawDesc)))
	})
	return file_skill_skill_proto_rawDescData
}

var file_skill_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_skill_skill_proto_goTypes = []any{
	(*IngestSkillRequest)(nil),    // 0: skill.IngestSkillRequest
	(*RuleFileEntry)(nil),         // 1: skill.RuleFileEntry
	(*IngestSkillResponse)(nil),   // 2: skill.IngestSkillResponse
	(*SearchSkillsRequest)(nil),   // 3: skill.SearchSkillsRequest
	(*SearchSkillsResponse)(nil),  // 4: skill.SearchSkillsResponse
	(*SkillSearchResult)(nil),     // 5: skill.SkillSearchResult
	(*SkillInfo)(nil),             // 6: skill.SkillInfo
	(*SkillChunkResult)(nil),      // 7: skill.SkillChunkResult
	(*ListSkillsRequest)(nil),     // 8: skill.ListSkillsRequest
	(*ListSkillsResponse)(nil),    // 9: skill.ListSkillsResponse
	(*GetSkillRequest)(nil),       // 10: skill.GetSkillRequest
	(*GetSkillResponse)(nil),      // 11: skill.GetSkillResponse
	(*DeleteSkillRequest)(nil),    // 12: skill.DeleteSkillRequest
	(*DeleteSkillResponse)(nil),   // 13: skill.DeleteSkillResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_skill_skill_proto_depIdxs = []int32{
	1,  // 0: skill.IngestSkillRequest.rules:type_name -> skill.RuleFileEntry
	5,  // 1: skill.SearchSkillsResponse.results:type_name -> skill.SkillSearchResult
	6,  // 2: skill.SkillSearchResult.skill:type_name -> skill.SkillInfo
	7,  // 3: skill.SkillSearchResult.chunks:type_name -> skill.SkillChunkResult
	14, // 4: skill.SkillInfo.created_at:type_name -> google.protobuf.Timestamp
	14, // 5: skill.SkillInfo.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 6: skill.ListSkillsResponse.skills:type_name -> skill.SkillInfo
	6,  // 7: skill.GetSkillResponse.skill:type_name -> skill.SkillInfo
	7,  // 8: skill.GetSkillResponse.chunks:type_name -> skill.SkillChunkResult
	0,  // 9: skill.SkillService.IngestSkill:input_type -> skill.IngestSkillRequest
	3,  // 10: skill.SkillService.SearchSkills:input_type -> skill.SearchSkillsRequest
	8,  // 11: skill.SkillService.ListSkills:input_type -> skill.ListSkillsRequest
	10, // 12: skill.SkillService.GetSkill:input_type -> skill.GetSkillRequest
	12, // 13: skill.SkillService.DeleteSkill:input_type -> skill.DeleteSkillRequest
	2,  // 14: skill.SkillService.IngestSkill:output_type -> skill.IngestSkillResponse
	4,  // 15: skill.SkillService.SearchSkills:output_type -> skill.SearchSkillsResponse
	9,  // 16: skill.SkillService.ListSkills:output_type -> skill.ListSkillsResponse
	11, // 17: skill.SkillService.GetSkill:output_type -> skill.GetSkillResponse
	13, // 18: skill.SkillService.DeleteSkill:output_type -> skill.DeleteSkillResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_skill_skill_proto_init() }
func file_skill_skill_proto_init() {
	if File_skill_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skill_skill_proto_rawDesc), len(file_skill_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skill_skill_proto_goTypes,
		DependencyIndexes: file_skill_skill_proto_depIdxs,
		MessageInfos:      file_skill_skill_proto_msgTypes,
	}.Build()
	File_skill_skill_proto = out.File
	file_skill_skill_proto_goTypes = nil
	file_skill_skill_proto_depIdxs = nil
}
