// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: memory/memory.proto

package memorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_memory_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{0}
}

func (x *StoreRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StoreRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoreRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StoreRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *StoreRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *StoreRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_memory_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{1}
}

func (x *StoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Scope           string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Tags            []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	MetaFiltersJson string                 `protobuf:"bytes,5,opt,name=meta_filters_json,json=metaFiltersJson,proto3" json:"meta_filters_json,omitempty"`
	Limit           int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_memory_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SearchRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SearchRequest) GetMetaFiltersJson() string {
	if x != nil {
		return x.MetaFiltersJson
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_memory_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Knowledge     *Knowledge             `protobuf:"bytes,1,opt,name=knowledge,proto3" json:"knowledge,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_memory_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResult) GetKnowledge() *Knowledge {
	if x != nil {
		return x.Knowledge
	}
	return nil
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RecallRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Task            string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Current         []string               `protobuf:"bytes,2,rep,name=current,proto3" json:"current,omitempty"`
	Trigger         string                 `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Budget          int32                  `protobuf:"varint,4,opt,name=budget,proto3" json:"budget,omitempty"`
	Limit           int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Scope           string                 `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	Tags            []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Type            string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	MetaFiltersJson string                 `protobuf:"bytes,9,opt,name=meta_filters_json,json=metaFiltersJson,proto3" json:"meta_filters_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecallRequest) Reset() {
	*x = RecallRequest{}
	mi := &file_memory_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallRequest) ProtoMessage() {}

func (x *RecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallRequest.ProtoReflect.Descriptor instead.
func (*RecallRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{5}
}

func (x *RecallRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *RecallRequest) GetCurrent() []string {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *RecallRequest) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *RecallRequest) GetBudget() int32 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *RecallRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RecallRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *RecallRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RecallRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RecallRequest) GetMetaFiltersJson() string {
	if x != nil {
		return x.MetaFiltersJson
	}
	return ""
}

type RecalledMemory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *SearchResult          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecalledMemory) Reset() {
	*x = RecalledMemory{}
	mi := &file_memory_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecalledMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecalledMemory) ProtoMessage() {}

func (x *RecalledMemory) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecalledMemory.ProtoReflect.Descriptor instead.
func (*RecalledMemory) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{6}
}

func (x *RecalledMemory) GetResult() *SearchResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RecalledMemory) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RecallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Trigger       string                 `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Budget        int32                  `protobuf:"varint,3,opt,name=budget,proto3" json:"budget,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Coverage      string                 `protobuf:"bytes,5,opt,name=coverage,proto3" json:"coverage,omitempty"`
	Keep          []string               `protobuf:"bytes,6,rep,name=keep,proto3" json:"keep,omitempty"`
	Add           []string               `protobuf:"bytes,7,rep,name=add,proto3" json:"add,omitempty"`
	Drop          []string               `protobuf:"bytes,8,rep,name=drop,proto3" json:"drop,omitempty"`
	Conflicts     []string               `protobuf:"bytes,9,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	Memories      []*RecalledMemory      `protobuf:"bytes,10,rep,name=memories,proto3" json:"memories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallResponse) Reset() {
	*x = RecallResponse{}
	mi := &file_memory_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallResponse) ProtoMessage() {}

func (x *RecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallResponse.ProtoReflect.Descriptor instead.
func (*RecallResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{7}
}

func (x *RecallResponse) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *RecallResponse) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *RecallResponse) GetBudget() int32 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *RecallResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RecallResponse) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

func (x *RecallResponse) GetKeep() []string {
	if x != nil {
		return x.Keep
	}
	return nil
}

func (x *RecallResponse) GetAdd() []string {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *RecallResponse) GetDrop() []string {
	if x != nil {
		return x.Drop
	}
	return nil
}

func (x *RecallResponse) GetConflicts() []string {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *RecallResponse) GetMemories() []*RecalledMemory {
	if x != nil {
		return x.Memories
	}
	return nil
}

type Knowledge struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	MetadataJson    string                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Tags            []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Scope           string                 `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`
	ParentId        string                 `protobuf:"bytes,8,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ChunkIndex      int32                  `protobuf:"varint,9,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	NormalizedTitle string                 `protobuf:"bytes,10,opt,name=normalized_title,json=normalizedTitle,proto3" json:"normalized_title,omitempty"`
	ContentHash     string                 `protobuf:"bytes,11,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Knowledge) Reset() {
	*x = Knowledge{}
	mi := &file_memory_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Knowledge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Knowledge) ProtoMessage() {}

func (x *Knowledge) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Knowledge.ProtoReflect.Descriptor instead.
func (*Knowledge) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{8}
}

func (x *Knowledge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Knowledge) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Knowledge) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Knowledge) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Knowledge) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *Knowledge) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Knowledge) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Knowledge) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Knowledge) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *Knowledge) GetNormalizedTitle() string {
	if x != nil {
		return x.NormalizedTitle
	}
	return ""
}

func (x *Knowledge) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *Knowledge) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Knowledge) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_memory_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{9}
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Knowledge           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_memory_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{10}
}

func (x *ListResponse) GetItems() []*Knowledge {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_memory_memory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_memory_memory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VerifiedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	VerifiedBy    string                 `protobuf:"bytes,3,opt,name=verified_by,json=verifiedBy,proto3" json:"verified_by,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	HasConfidence bool                   `protobuf:"varint,5,opt,name=has_confidence,json=hasConfidence,proto3" json:"has_confidence,omitempty"`
	SourceRef     string                 `protobuf:"bytes,6,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_memory_memory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerifyRequest) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *VerifyRequest) GetVerifiedBy() string {
	if x != nil {
		return x.VerifiedBy
	}
	return ""
}

func (x *VerifyRequest) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *VerifyRequest) GetHasConfidence() bool {
	if x != nil {
		return x.HasConfidence
	}
	return false
}

func (x *VerifyRequest) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_memory_memory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

type SupersedeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReplacementId string                 `protobuf:"bytes,2,opt,name=replacement_id,json=replacementId,proto3" json:"replacement_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupersedeRequest) Reset() {
	*x = SupersedeRequest{}
	mi := &file_memory_memory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupersedeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupersedeRequest) ProtoMessage() {}

func (x *SupersedeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupersedeRequest.ProtoReflect.Descriptor instead.
func (*SupersedeRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{15}
}

func (x *SupersedeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SupersedeRequest) GetReplacementId() string {
	if x != nil {
		return x.ReplacementId
	}
	return ""
}

type SupersedeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupersedeResponse) Reset() {
	*x = SupersedeResponse{}
	mi := &file_memory_memory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupersedeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupersedeResponse) ProtoMessage() {}

func (x *SupersedeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupersedeResponse.ProtoReflect.Descriptor instead.
func (*SupersedeResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{16}
}

func (x *SupersedeResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

type AuditRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scope          string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	UnverifiedDays int32                  `protobuf:"varint,2,opt,name=unverified_days,json=unverifiedDays,proto3" json:"unverified_days,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditRequest) Reset() {
	*x = AuditRequest{}
	mi := &file_memory_memory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRequest) ProtoMessage() {}

func (x *AuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRequest.ProtoReflect.Descriptor instead.
func (*AuditRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{17}
}

func (x *AuditRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *AuditRequest) GetUnverifiedDays() int32 {
	if x != nil {
		return x.UnverifiedDays
	}
	return 0
}

type AuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportJson    string                 `protobuf:"bytes,1,opt,name=report_json,json=reportJson,proto3" json:"report_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditResponse) Reset() {
	*x = AuditResponse{}
	mi := &file_memory_memory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditResponse) ProtoMessage() {}

func (x *AuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditResponse.ProtoReflect.Descriptor instead.
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{18}
}

func (x *AuditResponse) GetReportJson() string {
	if x != nil {
		return x.ReportJson
	}
	return ""
}

type CompactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threshold     float32                `protobuf:"fixed32,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Revector      bool                   `protobuf:"varint,2,opt,name=revector,proto3" json:"revector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactRequest) Reset() {
	*x = CompactRequest{}
	mi := &file_memory_memory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactRequest) ProtoMessage() {}

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{19}
}

func (x *CompactRequest) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CompactRequest) GetRevector() bool {
	if x != nil {
		return x.Revector
	}
	return false
}

type CompactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemovedCount  int32                  `protobuf:"varint,1,opt,name=removed_count,json=removedCount,proto3" json:"removed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactResponse) Reset() {
	*x = CompactResponse{}
	mi := &file_memory_memory_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResponse) ProtoMessage() {}

func (x *CompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResponse.ProtoReflect.Descriptor instead.
func (*CompactResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{20}
}

func (x *CompactResponse) GetRemovedCount() int32 {
	if x != nil {
		return x.RemovedCount
	}
	return 0
}

var File_memory_memory_proto protoreflect.FileDescriptor

const file_memory_memory_proto_rawDesc = "" +
	"\n" +
	"\x13memory/memory.proto\x12\x06memory\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x01\n" +
	"\fStoreRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12#\n" +
	"\rmetadata_json\x18\x04 \x01(\tR\fmetadataJson\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"\x1f\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa5\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12*\n" +
	"\x11meta_filters_json\x18\x05 \x01(\tR\x0fmetaFiltersJson\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"@\n" +
	"\x0eSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.memory.SearchResultR\aresults\"U\n" +
	"\fSearchResult\x12/\n" +
	"\tknowledge\x18\x01 \x01(\v2\x11.memory.KnowledgeR\tknowledge\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\"\xef\x01\n" +
	"\rRecallRequest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x18\n" +
	"\acurrent\x18\x02 \x03(\tR\acurrent\x12\x18\n" +
	"\atrigger\x18\x03 \x01(\tR\atrigger\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\x05R\x06budget\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05scope\x18\x06 \x01(\tR\x05scope\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12*\n" +
	"\x11meta_filters_json\x18\t \x01(\tR\x0fmetaFiltersJson\"V\n" +
	"\x0eRecalledMemory\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.memory.SearchResultR\x06result\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x94\x02\n" +
	"\x0eRecallResponse\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x18\n" +
	"\atrigger\x18\x02 \x01(\tR\atrigger\x12\x16\n" +
	"\x06budget\x18\x03 \x01(\x05R\x06budget\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bcoverage\x18\x05 \x01(\tR\bcoverage\x12\x12\n" +
	"\x04keep\x18\x06 \x03(\tR\x04keep\x12\x10\n" +
	"\x03add\x18\a \x03(\tR\x03add\x12\x12\n" +
	"\x04drop\x18\b \x03(\tR\x04drop\x12\x1c\n" +
	"\tconflicts\x18\t \x03(\tR\tconflicts\x122\n" +
	"\bmemories\x18\n" +
	" \x03(\v2\x16.memory.RecalledMemoryR\bmemories\"\xb0\x03\n" +
	"\tKnowledge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\tR\fmetadataJson\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x14\n" +
	"\x05scope\x18\a \x01(\tR\x05scope\x12\x1b\n" +
	"\tparent_id\x18\b \x01(\tR\bparentId\x12\x1f\n" +
	"\vchunk_index\x18\t \x01(\x05R\n" +
	"chunkIndex\x12)\n" +
	"\x10normalized_title\x18\n" +
	" \x01(\tR\x0fnormalizedTitle\x12!\n" +
	"\fcontent_hash\x18\v \x01(\tR\vcontentHash\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\";\n" +
	"\vListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"7\n" +
	"\fListResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.memory.KnowledgeR\x05items\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe3\x01\n" +
	"\rVerifyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\vverified_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x12\x1f\n" +
	"\vverified_by\x18\x03 \x01(\tR\n" +
	"verifiedBy\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12%\n" +
	"\x0ehas_confidence\x18\x05 \x01(\bR\rhasConfidence\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x06 \x01(\tR\tsourceRef\"5\n" +
	"\x0eVerifyResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount\"I\n" +
	"\x10SupersedeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0ereplacement_id\x18\x02 \x01(\tR\rreplacementId\"8\n" +
	"\x11SupersedeResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount\"M\n" +
	"\fAuditRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12'\n" +
	"\x0funverified_days\x18\x02 \x01(\x05R\x0eunverifiedDays\"0\n" +
	"\rAuditResponse\x12\x1f\n" +
	"\vreport_json\x18\x01 \x01(\tR\n" +
	"reportJson\"J\n" +
	"\x0eCompactRequest\x12\x1c\n" +
	"\tthreshold\x18\x01 \x01(\x02R\tthreshold\x12\x1a\n" +
	"\brevector\x18\x02 \x01(\bR\brevector\"6\n" +
	"\x0fCompactResponse\x12#\n" +
	"\rremoved_count\x18\x01 \x01(\x05R\fremovedCount2\x90\x04\n" +
	"\rMemoryService\x124\n" +
	"\x05Store\x12\x14.memory.StoreRequest\x1a\x15.memory.StoreResponse\x127\n" +
	"\x06Search\x12\x15.memory.SearchRequest\x1a\x16.memory.SearchResponse\x127\n" +
	"\x06Recall\x12\x15.memory.RecallRequest\x1a\x16.memory.RecallResponse\x121\n" +
	"\x04List\x12\x13.memory.ListRequest\x1a\x14.memory.ListResponse\x127\n" +
	"\x06Delete\x12\x15.memory.DeleteRequest\x1a\x16.memory.DeleteResponse\x127\n" +
	"\x06Verify\x12\x15.memory.VerifyRequest\x1a\x16.memory.VerifyResponse\x12@\n" +
	"\tSupersede\x12\x18.memory.SupersedeRequest\x1a\x19.memory.SupersedeResponse\x124\n" +
	"\x05Audit\x12\x14.memory.AuditRequest\x1a\x15.memory.AuditResponse\x12:\n" +
	"\aCompact\x12\x16.memory.CompactRequest\x1a\x17.memory.CompactResponseB.Z,github.com/trungtran/coder/api/grpc/memorypbb\x06proto3"

var (
	file_memory_memory_proto_rawDescOnce sync.Once
	file_memory_memory_proto_rawDescData []byte
)

func file_memory_memory_proto_rawDescGZIP() []byte {
	file_memory_memory_proto_rawDescOnce.Do(func() {
		file_memory_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_memory_proto_rawDesc), len(file_memory_memory_proto_rawDesc)))
	})
	return file_memory_memory_proto_rawDescData
}

var file_memory_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_memory_memory_proto_goTypes = []any{
	(*StoreRequest)(nil),          // 0: memory.StoreRequest
	(*StoreResponse)(nil),         // 1: memory.StoreResponse
	(*SearchRequest)(nil),         // 2: memory.SearchRequest
	(*SearchResponse)(nil),        // 3: memory.SearchResponse
	(*SearchResult)(nil),          // 4: memory.SearchResult
	(*RecallRequest)(nil),         // 5: memory.RecallRequest
	(*RecalledMemory)(nil),        // 6: memory.RecalledMemory
	(*RecallResponse)(nil),        // 7: memory.RecallResponse
	(*Knowledge)(nil),             // 8: memory.Knowledge
	(*ListRequest)(nil),           // 9: memory.ListRequest
	(*ListResponse)(nil),          // 10: memory.ListResponse
	(*DeleteRequest)(nil),         // 11: memory.DeleteRequest
	(*DeleteResponse)(nil),        // 12: memory.DeleteResponse
	(*VerifyRequest)(nil),         // 13: memory.VerifyRequest
	(*VerifyResponse)(nil),        // 14: memory.VerifyResponse
	(*SupersedeRequest)(nil),      // 15: memory.SupersedeRequest
	(*SupersedeResponse)(nil),     // 16: memory.SupersedeResponse
	(*AuditRequest)(nil),          // 17: memory.AuditRequest
	(*AuditResponse)(nil),         // 18: memory.AuditResponse
	(*CompactRequest)(nil),        // 19: memory.CompactRequest
	(*CompactResponse)(nil),       // 20: memory.CompactResponse
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_memory_memory_proto_depIdxs = []int32{
	4,  // 0: memory.SearchResponse.results:type_name -> memory.SearchResult
	8,  // 1: memory.SearchResult.knowledge:type_name -> memory.Knowledge
	4,  // 2: memory.RecalledMemory.result:type_name -> memory.SearchResult
	6,  // 3: memory.RecallResponse.memories:type_name -> memory.RecalledMemory
	21, // 4: memory.Knowledge.created_at:type_name -> google.protobuf.Timestamp
	21, // 5: memory.Knowledge.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 6: memory.ListResponse.items:type_name -> memory.Knowledge
	21, // 7: memory.VerifyRequest.verified_at:type_name -> google.protobuf.Timestamp
	0,  // 8: memory.MemoryService.Store:input_type -> memory.StoreRequest
	2,  // 9: memory.MemoryService.Search:input_type -> memory.SearchRequest
	5,  // 10: memory.MemoryService.Recall:input_type -> memory.RecallRequest
	9,  // 11: memory.MemoryService.List:input_type -> memory.ListRequest
	11, // 12: memory.MemoryService.Delete:input_type -> memory.DeleteRequest
	13, // 13: memory.MemoryService.Verify:input_type -> memory.VerifyRequest
	15, // 14: memory.MemoryService.Supersede:input_type -> memory.SupersedeRequest
	17, // 15: memory.MemoryService.Audit:input_type -> memory.AuditRequest
	19, // 16: memory.MemoryService.Compact:input_type -> memory.CompactRequest
	1,  // 17: memory.MemoryService.Store:output_type -> memory.StoreResponse
	3,  // 18: memory.MemoryService.Search:output_type -> memory.SearchResponse
	7,  // 19: memory.MemoryService.Recall:output_type -> memory.RecallResponse
	10, // 20: memory.MemoryService.List:output_type -> memory.ListResponse
	12, // 21: memory.MemoryService.Delete:output_type -> memory.DeleteResponse
	14, // 22: memory.MemoryService.Verify:output_type -> memory.VerifyResponse
	16, // 23: memory.MemoryService.Supersede:output_type -> memory.SupersedeResponse
	18, // 24: memory.MemoryService.Audit:output_type -> memory.AuditResponse
	20, // 25: memory.MemoryService.Compact:output_type -> memory.CompactResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_memory_memory_proto_init() }
func file_memory_memory_proto_init() {
	if File_memory_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_memory_proto_rawDesc), len(file_memory_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memory_memory_proto_goTypes,
		DependencyIndexes: file_memory_memory_proto_depIdxs,
		MessageInfos:      file_memory_memory_proto_msgTypes,
	}.Build()
	File_memory_memory_proto = out.File
	file_memory_memory_proto_goTypes = nil
	file_memory_memory_proto_depIdxs = nil
}
